export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const ADD_WDEETS = 'ADD_WDEETS';
export const ADD_MYPROFILEDETAILS = 'ADD_MYPROFILEDETAILS';
export const ADD_MARKETPRICES = 'ADD_MARKETPRICES';
export const ADD_EMOJICOLOR = 'ADD_EMOJICOLOR';
export const ADD_USERDETAILS = 'ADD_USERDETAILS';
export const ADD_TOKENBALANCES = 'ADD_TOKENBALANCES';
export const ADD_MYNFTS = 'ADD_MYNFTS';

// secret settings
export const ADD_SECRETSETTINGS = 'ADD_SECRETSETTINGS';

// on chain
export const ADD_HOMORAV2FARMS = 'ADD_HOMORAV2FARMS';
export const ADD_HOMORAV2APYS = 'ADD_HOMORAV2APYS';
export const ADD_HOMORAV2TRADINGVOLS = 'ADD_HOMORAV2TRADINGVOLS';
