export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const ADD_WDEETS = 'ADD_WDEETS';
export const ADD_MYPROFILEDETAILS = 'ADD_MYPROFILEDETAILS';
export const ADD_MYAPPS = 'ADD_MYAPPS';
export const ADD_DISCOVERAPPS = 'ADD_DISCOVERAPPS';
export const ADD_MARKETPRICES = 'ADD_MARKETPRICES';
export const ADD_EMOJICOLOR = 'ADD_EMOJICOLOR';
export const ADD_USERDETAILS = 'ADD_USERDETAILS';
export const ADD_TOKENBALANCES = 'ADD_TOKENBALANCES';

// all dapps redux types
export const ADD_UNISWAPTOKENLIST = 'ADD_UNISWAPTOKENLIST';
export const ADD_UNISWAPSTAKEPOOLS = 'ADD_UNISWAPSTAKEPOOLS';
export const ADD_MEMECOINSLIST = 'ADD_MEMECOINSLIST';
